version: "3"

services:
    bot:
        build:
            context: .
        container_name: support-bot
        command: sh -c "cd /usr/src/app && python -m app"
        restart: always
        volumes:
            - .:/usr/src/app
        networks:
            - network
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    network:
